// ═══════════════════════════════════════════════════════════════
// Sidebar Navigation — DERIVED from the module registry (ADR-0005)
//
// This file used to BE the navigation: a hardcoded 165-line array that had to be
// mirrored by hand into tests/e2e/app-routes.ts, and had drifted from it.
// It is now a presentation adapter: the registry owns labels, hrefs, order and
// flags; this file only turns icon NAMES into lucide components, because the
// registry must stay importable from non-React contexts (the e2e route matrix).
//
// To add a surface, add it to src/lib/modules/registry.ts. Do not edit this file
// unless you are adding an icon.
// ═══════════════════════════════════════════════════════════════

import {
  Terminal, FileText, Database, Clock, Shield, Zap,
  Cpu, Activity, Layers, HardDrive, Wrench, ListTodo, Globe, Globe2,
  ScrollText, Sparkles, Rocket, Volume2, Mic, GitBranch,
  RotateCcw, ShieldCheck, Lock, Code,
  BookOpen, Bot, MessageCircle,
  AudioLines, Settings2, Network, BarChart3, Trophy, Telescope, Workflow,
  FileStack, Settings, LifeBuoy, CalendarClock,
} from "lucide-react";

import type { AccentColor } from "@/types/console";
import type { FeatureFlag } from "@/lib/feature-flags";
import { MODULES } from "@/lib/modules/registry";
import { NAV_SECTIONS } from "@/lib/modules/types";
import type { IconName, NavLink as ModuleNavLink, NavSectionLabel } from "@/lib/modules/types";

// ── Types ──────────────────────────────────────────────────────

export interface SidebarLink {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  href: string;
  color: AccentColor;
  /** When set, the link is hidden while that feature flag is disabled. */
  featureFlag?: FeatureFlag;
}

export interface SidebarSection {
  label: NavSectionLabel;
  links: SidebarLink[];
}

// ── Icon resolution ────────────────────────────────────────────

/**
 * Exhaustive over IconName, so adding a name to the registry without an icon
 * here is a compile error rather than a blank space in the sidebar.
 */
const ICONS: Record<IconName, React.ComponentType<{ className?: string }>> = {
  Zap, Clock, Database, ScrollText,
  Rocket, Workflow, Terminal, MessageCircle,
  Bot, FileText, Wrench, Sparkles,
  BarChart3, Trophy, Telescope, FileStack,
  BookOpen, Globe, Cpu, Lock,
  RotateCcw, Activity, Layers, HardDrive,
  Globe2, Code, Shield, ShieldCheck,
  AudioLines, Mic, Volume2, GitBranch,
  ListTodo, Network, Settings2, CalendarClock,
  Settings, LifeBuoy,
};

function toSidebarLink(link: ModuleNavLink): SidebarLink {
  return {
    icon: ICONS[link.icon],
    label: link.label,
    href: link.href,
    color: link.color,
    ...(link.featureFlag ? { featureFlag: link.featureFlag } : {}),
  };
}

// ── Derived navigation ─────────────────────────────────────────

/**
 * The five sections in their fixed order, each holding every module's links
 * for that section sorted by `order`. A section no module contributes to is
 * left out rather than rendered empty.
 */
export const mainSections: SidebarSection[] = NAV_SECTIONS.flatMap((label) => {
  const links = MODULES.flatMap((mod) =>
    (mod.nav ?? [])
      .filter((section) => section.label === label)
      .flatMap((section) => section.links),
  ).sort((a, b) => a.order - b.order);
  return links.length ? [{ label, links: links.map(toSidebarLink) }] : [];
});
