/** @jest-environment jsdom */
/* eslint-disable @typescript-eslint/no-require-imports -- the route and the
   loader under contract do not exist in the tree yet, so a static import would
   not compile. The requires sit inside helpers called from each test, so a
   missing file fails every test with the contract sentence rather than
   collapsing the suite before a single assertion runs. */

// ═══════════════════════════════════════════════════════════════
// B16 oracle, the Help screen: src/app/help/[[...slug]]/page.tsx.
//
// Contract section 3. The Help page is a SERVER component (the first one in
// the app; every other page.tsx is "use client"), so it is awaited and its
// returned tree is rendered. It renders the fragment inside AppPageShell and
// PageHeader with HelpNav, HelpSearch and prev/next, and NO iframe: decision 3
// said iframe, B16's bullet overrules it, and an oracle that did not say so
// would let the cheaper answer back in.
//
// The corpus is a REAL one, written to a temp directory and pointed at with
// PS_HELP_DIR (contract 2.2), not a module double. public/help/ is git-ignored
// and generated by B15's prebuild, so a test that read the checkout's copy
// would be green on the operator's machine and red on a fresh clone; and a
// test that doubled the loader would prove the page renders whatever it is
// handed while proving nothing about the file it is meant to read. The env
// override exists precisely so the isolated instance and this oracle can hand
// it a corpus.
//
// Only recordEvent is doubled, because the alternative is a database.
// ═══════════════════════════════════════════════════════════════

import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { render, screen, within } from "@testing-library/react";
import type { ReactElement } from "react";

import { labelFor } from "@/lib/modules/registry";

// ── Module doubles ──────────────────────────────────────────────

const mockNav = { pathname: "/help" };

jest.mock("next/navigation", () => ({
  usePathname: () => mockNav.pathname,
  useRouter: () => ({ push: jest.fn(), replace: jest.fn(), prefetch: jest.fn() }),
  useSearchParams: () => new URLSearchParams(),
  notFound: () => {
    throw new Error("NEXT_NOT_FOUND");
  },
}));

jest.mock("next/link", () => require("../helpers/mocks").nextLinkMock());

jest.mock("lucide-react", () => require("../helpers/mocks").lucideMock());

const mockRecordEvent = jest.fn();
jest.mock("@/lib/analytics/record-event", () => ({
  recordEvent: (...args: unknown[]) => mockRecordEvent(...args),
}));

// ── The page under contract ─────────────────────────────────────

type HelpPageComponent = (props: {
  params: Promise<{ slug?: string[] }>;
}) => Promise<ReactElement>;

function helpPage(): HelpPageComponent {
  let mod: { default?: unknown };
  try {
    mod = require("../../src/app/help/[[...slug]]/page") as { default?: unknown };
  } catch (err) {
    throw new Error(
      "B16 owes src/app/help/[[...slug]]/page.tsx (contract 3.1). require() said: " + String(err),
    );
  }
  if (typeof mod.default !== "function") {
    throw new Error("src/app/help/[[...slug]]/page.tsx must default-export the page (contract 3.1).");
  }
  return mod.default as HelpPageComponent;
}

/** The loader's cache is per process, so each test clears it after moving
 *  PS_HELP_DIR. Silent while the module is missing: the page's own require
 *  says which file B16 owes, and one sentence per test is enough. */
function resetHelpCache(): void {
  try {
    const mod = require("@/lib/help/help-source") as { resetHelpCache?: () => void };
    mod.resetHelpCache?.();
  } catch {
    /* B16 owes src/lib/help/help-source.ts (contract 2.2). */
  }
}

async function renderHelp(slug?: string[]): Promise<HTMLElement> {
  const Page = helpPage();
  const ui = await Page({ params: Promise.resolve(slug ? { slug } : {}) });
  return render(ui).container;
}

// ── The corpus on disk (contract 0.1 - 0.6) ─────────────────────

const MISSIONS_FRAGMENT =
  '<h2 id="dispatching">Dispatching</h2><p>A fixture body for the Missions guide.</p>';
const INDEX_FRAGMENT = "<p>A fixture body for the first page.</p>";

const MANIFEST = {
  generatedAt: "2026-09-05T00:00:00.000Z",
  pages: [
    {
      slug: "start-here/what-it-is",
      title: "What PatterStage is",
      summary: "The console, in one page.",
      section: "start-here",
      nav: 1,
    },
    {
      slug: "start-here/tour/missions",
      title: "Tour: Missions",
      summary: "What you see, and what to do here.",
      section: "start-here",
      nav: 2,
      screen: "/work/missions",
    },
    {
      slug: "guides/dashboard",
      title: "Dashboard",
      summary: "The operations board.",
      section: "guides",
      nav: 1,
      screen: "/",
    },
    {
      slug: "guides/work-missions",
      title: "Missions",
      summary: "Dispatch work, watch it run, schedule it to repeat.",
      section: "guides",
      nav: 2,
      screen: "/work/missions",
    },
    {
      slug: "reference/api",
      title: "API",
      summary: "Every route the app answers.",
      section: "reference",
      nav: 1,
    },
  ],
};

const CONCEPTS = {
  generatedAt: "2026-09-05T00:00:00.000Z",
  concepts: [
    {
      id: "mission",
      term: "Mission",
      short: "One piece of work you hand the agent.",
      slug: "concepts/mission",
    },
  ],
};

const SEARCH = {
  generatedAt: "2026-09-05T00:00:00.000Z",
  entries: [
    { slug: "guides/work-missions", title: "Missions", section: "guides", text: "Dispatch work." },
    {
      slug: "guides/work-missions",
      title: "Missions",
      section: "guides",
      heading: "Dispatching",
      anchor: "dispatching",
      text: "Pick a template and send it.",
    },
  ],
};

let sandbox = "";
let builtDir = "";
let emptyDir = "";
const savedEnv = { ...process.env };

function write(path: string, body: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body, "utf-8");
}

beforeAll(() => {
  sandbox = mkdtempSync(join(tmpdir(), "ps-b16-help-"));
  builtDir = join(sandbox, "built");
  emptyDir = join(sandbox, "not-built");
  mkdirSync(emptyDir, { recursive: true });

  write(join(builtDir, "manifest.json"), JSON.stringify(MANIFEST));
  write(join(builtDir, "concepts.json"), JSON.stringify(CONCEPTS));
  write(join(builtDir, "search.json"), JSON.stringify(SEARCH));
  write(join(builtDir, "fragments", "start-here", "what-it-is.html"), INDEX_FRAGMENT);
  write(join(builtDir, "fragments", "start-here", "tour", "missions.html"), "<p>The tour stop.</p>");
  write(join(builtDir, "fragments", "guides", "dashboard.html"), "<p>The board.</p>");
  write(join(builtDir, "fragments", "guides", "work-missions.html"), MISSIONS_FRAGMENT);
  // reference/api is in the manifest with NO fragment on purpose: contract 3.3.

  // Plantable proof that a traversal is refused rather than served.
  write(join(sandbox, "secret.html"), "<p>NOT-FOR-THE-BROWSER</p>");
});

afterAll(() => {
  process.env = { ...savedEnv };
  if (sandbox) rmSync(sandbox, { recursive: true, force: true });
});

beforeEach(() => {
  mockNav.pathname = "/help";
  mockRecordEvent.mockClear();
  process.env.PS_HELP_DIR = builtDir;
  resetHelpCache();
});

afterEach(() => {
  delete process.env.PS_HELP_DIR;
  resetHelpCache();
});

function useUnbuiltCorpus(): void {
  process.env.PS_HELP_DIR = emptyDir;
  resetHelpCache();
}

// ── The control, green today ────────────────────────────────────

describe("the rail entry the Help screen answers", () => {
  it("is a registry route, so /help is not a page nobody can reach", () => {
    expect(labelFor("/help")).toBe("Help");
    expect(labelFor("/help/guides/work-missions")).toBe("Help");
  });
});

// ── The frame and the fragment (contract 3.1, 3.2, 3.3) ─────────

describe("the Help page renders one guide inside the app's own frame", () => {
  it("heads the page with the guide's title and summary, not the word Help", async () => {
    mockNav.pathname = "/help/guides/work-missions";
    await renderHelp(["guides", "work-missions"]);
    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent("Missions");
    expect(
      screen.getByText("Dispatch work, watch it run, schedule it to repeat."),
    ).toBeInTheDocument();
  });

  it("renders the fragment file that belongs to the slug", async () => {
    mockNav.pathname = "/help/guides/work-missions";
    await renderHelp(["guides", "work-missions"]);
    const article = screen.getByTestId("help-fragment");
    expect(article).toHaveTextContent("A fixture body for the Missions guide.");
    expect(article).not.toHaveTextContent("A fixture body for the first page.");
    expect(within(article).getByRole("heading", { level: 2 })).toHaveTextContent("Dispatching");
  });

  it("uses no iframe: the fragment is this page's own DOM", async () => {
    mockNav.pathname = "/help/guides/work-missions";
    const container = await renderHelp(["guides", "work-missions"]);
    expect(container.querySelector("iframe")).toBeNull();
  });

  it("offers a named search box over the corpus", async () => {
    mockNav.pathname = "/help/guides/work-missions";
    await renderHelp(["guides", "work-missions"]);
    expect(screen.getByRole("searchbox", { name: /search/i })).toBeInTheDocument();
  });
});

// ── The nav (contract 3.3) ──────────────────────────────────────

describe("HelpNav lists the corpus and says where you are", () => {
  it("names a link for every page, grouped by tier", async () => {
    mockNav.pathname = "/help/guides/work-missions";
    await renderHelp(["guides", "work-missions"]);
    const nav = within(screen.getByRole("navigation", { name: "Help" }));
    for (const [name, href] of [
      ["What PatterStage is", "/help/start-here/what-it-is"],
      ["Tour: Missions", "/help/start-here/tour/missions"],
      ["Dashboard", "/help/guides/dashboard"],
      ["Missions", "/help/guides/work-missions"],
      ["API", "/help/reference/api"],
    ] as const) {
      expect(nav.getByRole("link", { name })).toHaveAttribute("href", href);
    }
    expect(nav.getByText("Start here")).toBeInTheDocument();
    expect(nav.getByText("Guides")).toBeInTheDocument();
  });

  it("marks the page you are on, and only that one", async () => {
    mockNav.pathname = "/help/guides/work-missions";
    await renderHelp(["guides", "work-missions"]);
    const nav = screen.getByRole("navigation", { name: "Help" });
    const current = within(nav)
      .getAllByRole("link")
      .filter((a) => a.getAttribute("aria-current") === "page");
    expect(current.map((a) => a.getAttribute("href"))).toEqual(["/help/guides/work-missions"]);
  });
});

// ── Prev and next (contract 3.3) ────────────────────────────────

describe("prev and next walk the reading order, not the alphabet", () => {
  it("names the page either side of this one", async () => {
    mockNav.pathname = "/help/guides/work-missions";
    await renderHelp(["guides", "work-missions"]);
    const chain = within(screen.getByRole("navigation", { name: "Help pages" }));
    expect(chain.getByRole("link", { name: "Previous: Dashboard" })).toHaveAttribute(
      "href",
      "/help/guides/dashboard",
    );
    expect(chain.getByRole("link", { name: "Next: API" })).toHaveAttribute(
      "href",
      "/help/reference/api",
    );
  });

  it("renders one link, not a dead control, at the front of the corpus", async () => {
    mockNav.pathname = "/help/start-here/what-it-is";
    await renderHelp(["start-here", "what-it-is"]);
    const chain = within(screen.getByRole("navigation", { name: "Help pages" }));
    expect(chain.queryByRole("link", { name: /^Previous:/ })).toBeNull();
    expect(chain.getByRole("link", { name: "Next: Tour: Missions" })).toBeInTheDocument();
  });
});

// ── /help itself, and the two ways a slug can be wrong (3.1) ────

describe("the address resolves before anything is read", () => {
  it("renders the first page of the reading order at /help, with no slug", async () => {
    await renderHelp();
    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent("What PatterStage is");
    expect(screen.getByTestId("help-fragment")).toHaveTextContent("A fixture body for the first page.");
  });

  it("404s a slug the manifest does not carry", async () => {
    mockNav.pathname = "/help/guides/nope";
    await expect(renderHelp(["guides", "nope"])).rejects.toThrow("NEXT_NOT_FOUND");
  });

  it("404s a traversal rather than serving what is above the corpus", async () => {
    mockNav.pathname = "/help/..";
    await expect(renderHelp(["..", "..", "secret"])).rejects.toThrow("NEXT_NOT_FOUND");
    expect(screen.queryByText(/NOT-FOR-THE-BROWSER/)).toBeNull();
  });
});

// ── The analytics emit (contract 3.5) ───────────────────────────

describe("help.opened is recorded from the server, once, for the page that rendered", () => {
  it("records the slug that was opened", async () => {
    mockNav.pathname = "/help/guides/work-missions";
    await renderHelp(["guides", "work-missions"]);
    expect(mockRecordEvent).toHaveBeenCalledTimes(1);
    expect(mockRecordEvent).toHaveBeenCalledWith("help.opened", {
      entityType: "help",
      entityId: "guides/work-missions",
    });
  });

  it("records the resolved index slug when /help is opened with no slug", async () => {
    await renderHelp();
    expect(mockRecordEvent).toHaveBeenCalledWith("help.opened", {
      entityType: "help",
      entityId: "start-here/what-it-is",
    });
  });

  it("records nothing for a page that 404s", async () => {
    mockNav.pathname = "/help/guides/nope";
    await expect(renderHelp(["guides", "nope"])).rejects.toThrow("NEXT_NOT_FOUND");
    expect(mockRecordEvent).not.toHaveBeenCalled();
  });
});

// ── The two empties (contract 3.6, 3.3) ─────────────────────────

describe("a corpus that has not been built says so, and does not 404 or crash", () => {
  it("names the command that builds it, and records nothing", async () => {
    useUnbuiltCorpus();
    await renderHelp();
    expect(screen.getByText(/has not been built/i)).toBeInTheDocument();
    expect(screen.getByText(/npm run docs:build/)).toBeInTheDocument();
    expect(mockRecordEvent).not.toHaveBeenCalled();
  });

  it("still renders the app frame, so the rail's Help entry leads somewhere", async () => {
    useUnbuiltCorpus();
    await renderHelp();
    expect(screen.getByRole("heading", { level: 1 })).toBeInTheDocument();
  });

  it("does not 404 a slug it cannot check", async () => {
    useUnbuiltCorpus();
    mockNav.pathname = "/help/guides/work-missions";
    await expect(renderHelp(["guides", "work-missions"])).resolves.toBeDefined();
  });
});

describe("a manifest entry whose fragment is missing is an alert, not an empty page", () => {
  it("says so rather than rendering a blank article", async () => {
    mockNav.pathname = "/help/reference/api";
    await renderHelp(["reference", "api"]);
    expect(screen.getByRole("alert")).toHaveTextContent(/docs:build/);
    expect(screen.queryByTestId("help-fragment")).toBeNull();
  });
});
