// ═══════════════════════════════════════════════════════════════
// help-source.ts — reading the built Help corpus off disk
//
// public/help/ is generated by scripts/docs/build-site.mjs at prebuild and is
// git-ignored, so a fresh clone has none of it until the first build. Every
// function here therefore returns the empty value rather than throwing: the
// Help page's job when the corpus is absent is to say how to build it, and a
// loader that threw would take the whole render with it.
//
// Server only. It is imported by the Help page and by the root layout, both
// server components; the client gets the two small indexes as props.
// ═══════════════════════════════════════════════════════════════

import { existsSync, readFileSync } from "fs";
import { join, resolve, sep } from "path";

import {
  isSafeHelpSlug,
  parseConcepts,
  parseHelpManifest,
  parseSearchIndex,
  type ConceptIndex,
  type HelpManifest,
  type HelpSearchEntry,
} from "./help-manifest";

/**
 * Where the corpus lives.
 *
 * PS_HELP_DIR overrides it, read at call time rather than at module load, so a
 * test or the isolated instance can point at a built corpus without a public/
 * in the checkout, and can move it between cases.
 *
 * @public Exported so a caller can say WHERE it looked when it found nothing:
 * "no corpus" and "no corpus at this path" are different sentences to read.
 */
export function helpRoot(): string {
  const override = process.env.PS_HELP_DIR;
  return override && override.trim() ? override : join(process.cwd(), "public", "help");
}

interface Cache {
  root: string;
  manifest?: HelpManifest;
  concepts?: ConceptIndex;
  search?: HelpSearchEntry[];
}

// Memoised per process: the layout reads the manifest on every request, and one
// readFileSync per process is the difference between that being free and being
// a syscall on every page view.
let cache: Cache = { root: "" };

function cacheFor(): Cache {
  const root = helpRoot();
  if (cache.root !== root) cache = { root };
  return cache;
}

/**
 * Forget what was read.
 *
 * @public For tests, which move PS_HELP_DIR between cases, and for a dev
 * watcher after a rebuild. Without it a process that read an empty corpus once
 * would go on reporting it empty for the rest of its life.
 */
export function resetHelpCache(): void {
  cache = { root: "" };
}

function readJson(name: string): unknown {
  const path = join(helpRoot(), name);
  try {
    if (!existsSync(path)) return null;
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    // Unreadable bytes, a half-written file mid-build, invalid JSON: all the
    // same answer, which is that there is no usable corpus right now.
    return null;
  }
}

export function loadHelpManifest(): HelpManifest {
  const c = cacheFor();
  if (!c.manifest) c.manifest = parseHelpManifest(readJson("manifest.json"));
  return c.manifest;
}

export function loadHelpConcepts(): ConceptIndex {
  const c = cacheFor();
  if (!c.concepts) c.concepts = parseConcepts(readJson("concepts.json"));
  return c.concepts;
}

export function loadHelpSearchIndex(): HelpSearchEntry[] {
  const c = cacheFor();
  if (!c.search) c.search = parseSearchIndex(readJson("search.json"));
  return c.search;
}

/**
 * True when there is a corpus worth rendering.
 *
 * @public The question a caller asks before deciding between the Help screen
 * and the "not built yet" panel, phrased once here rather than as
 * `.pages.length > 0` in each place that asks.
 */
export function helpIsBuilt(): boolean {
  return loadHelpManifest().pages.length > 0;
}

/**
 * One page's HTML body, or null.
 *
 * Two belts, deliberately, and the second is UNREACHABLE while the first
 * holds. isSafeHelpSlug admits no dot, no backslash and no leading slash, so a
 * slug that passes it cannot join its way out of the directory, and a mutation
 * sweep duly reports the resolved-path check as an equivalent mutant.
 *
 * It stays. The regex is one edit away from admitting a dot, and the day it
 * does, this line is the difference between a rendering bug and reading a file
 * off the operator's disk. A guard that is currently redundant and a guard that
 * is unnecessary are different things.
 */
export function loadHelpFragment(slug: string): string | null {
  if (!isSafeHelpSlug(slug)) return null;
  const fragments = join(helpRoot(), "fragments");
  const path = `${join(fragments, ...slug.split("/"))}.html`;
  const resolved = resolve(path);
  if (!resolved.startsWith(resolve(fragments) + sep)) return null;
  try {
    if (!existsSync(resolved)) return null;
    return readFileSync(resolved, "utf-8");
  } catch {
    return null;
  }
}

